"""Create categories table

Revision ID: 3f0731760a77
Revises: 8fdc8a71268b
Create Date: 2024-08-16 01:27:02.542046

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3f0731760a77'
down_revision = '8fdc8a71268b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    pass

    
    # ### end Alembic commands ###


def downgrade():
    pass
    
